# Sección nueva

In [ ]:
print('Hello World')

Hello World


In [ ]:
a, b, c = 10, 'Hello World', True

print(a)
print(b)
print(c)

10
Hello World
True


In [ ]:
variable_entera = 12
otra_variable_entera = 24519
variable_entera_negativa = 257

In [ ]:
print(variable_entera)
print(otra_variable_entera)

12
24519


In [ ]:
variable_flotante = 125.7
otra_variable_flotante = 2351.47044

In [ ]:
variable_entera = True
variable_false = False

In [ ]:
print(variable_entera)
print(variable_false)

True
False


In [ ]:
import sys 

print(sys.getsizeof(1.0))
print(sys.getsizeof(""))
print(sys.getsizeof("Hello!"))
print(sys.getsizeof(dict()))
print(sys.getsizeof(dict({'A':1, 'B':2})))

24
53
55
248
248


In [ ]:
nombre = input('Cual es tu nombre? ')

Cual es tu nombre? Noe


In [ ]:
print(nombre, type(nombre))

Noe <class 'str'>


In [ ]:
type(nombre)

str

In [ ]:
edad = 19

In [ ]:
print('Me llamo ' + nombre)
print('Mi edad es ' + str(edad))

Me llamo Noe
Mi edad es 19


In [ ]:
numero2 = int(input('Introduce un numero: '))
numero1= int(input('Introduce otro numero: '))

Introduce un numero: 10
Introduce otro numero: 20


In [ ]:
numero1 + numero2

30

In [ ]:
cadena = 'hola'
for i in cadena:
  print(i)

h
o
l
a


In [ ]:
lista = [1,3,7,"Hola"]
for e in lista:
  print(e)

1
3
7
Hola


In [ ]:
i = 1
while True:
  print(i)
  i = i + 1
  if(i > 3):
       break

1
2
3


In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
def saludo():
  print("Hola mundo")

In [ ]:
saludo()

Hola mundo


In [ ]:
def suma(a,b):
  return a + b

def resta(a,b):
  return a - b

In [ ]:
b = 10
print(suma(a,b))
print(resta(a,b))

20
0


In [ ]:
def doble(a,b):
  print(suma(a,b))
  print(resta(a,b)) 

In [ ]:
doble(a,b)

20
0


In [ ]:
import math as mt

In [ ]:
mt.sin(90)

0.8939966636005579

In [ ]:
mt.sqrt(90)

9.486832980505138

In [ ]:
mt.radians(90)

1.5707963267948966

In [ ]:
mt.factorial(90)

1485715964481761497309522733620825737885569961284688766942216863704985393094065876545992131370884059645617234469978112000000000000000000000

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [ ]:
numeros_rango = np.linspace(0,30,31)

print(np.linspace(0,30,10))

print("max", numeros_rango.max())

print("min", numeros_rango.min())

print("valor medio", numeros_rango.mean())

print("desviacion standar",  numeros_rango.std())

print("suma",  numeros_rango.sum())

print("mediana", np.median(numeros_rango))

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
max 30.0
min 0.0
valor medio 15.0
desviacion standar 8.94427190999916
suma 465.0
mediana 15.0


In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
A = np.array([[1,2,3],
[4,5,6], [7,8,9]])

print(A)

print(type(A))

Am = np.mat(A)

print(Am)

print(type(Am))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [ ]:
#Multipliacion de arreglos

print(str(A*A) + "\n")

#Multiplicacion de matrices

print(Am*Am)

#Transpuesta

print(Am.T)

#Diagonal

print(Am.diagonal())

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 5 9]]


In [ ]:
import random

items = ['hidalgo', 'jalisco', 'yucatan', 'queretaro', 'durango']



for i in range(20):

 print("un dado", random.randrange(1, 7))

 print("otro dado", random.randint(1, 6))

 print(random.random())

 #Acepta valores repetidos

 print(random.choices(items, k=2))

 #Muestreo sin repeticiones

print(random.sample(items, 2))

un dado 3
otro dado 5
0.9306715688919172
['jalisco', 'queretaro']
un dado 1
otro dado 1
0.977795551798342
['durango', 'jalisco']
un dado 3
otro dado 5
0.7076682181741677
['queretaro', 'hidalgo']
un dado 5
otro dado 4
0.9099607892335849
['hidalgo', 'durango']
un dado 1
otro dado 2
0.45098792046683056
['yucatan', 'jalisco']
un dado 4
otro dado 6
0.4576736388144317
['durango', 'hidalgo']
un dado 5
otro dado 1
0.15739410164309664
['hidalgo', 'yucatan']
un dado 6
otro dado 3
0.9774988274539059
['queretaro', 'jalisco']
un dado 5
otro dado 3
0.3536655202408434
['queretaro', 'yucatan']
un dado 6
otro dado 6
0.8761828322532101
['durango', 'hidalgo']
un dado 2
otro dado 6
0.9010133289800404
['yucatan', 'hidalgo']
un dado 2
otro dado 3
0.4404596109635428
['queretaro', 'hidalgo']
un dado 1
otro dado 6
0.4693322734578137
['yucatan', 'queretaro']
un dado 1
otro dado 4
0.3441563000720522
['hidalgo', 'yucatan']
un dado 2
otro dado 6
0.9929513956426673
['hidalgo', 'durango']
un dado 6
otro dado 3
0.047