In [8]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [9]:
sample_size = 10

dimension = 4
degree = 3

x = np.random.randn(sample_size, dimension)

In [10]:
x

array([[-0.28340803, -0.35691734, -0.75008725,  0.4268118 ],
       [-0.36018702,  0.6493908 ,  1.18606298, -0.71173282],
       [-0.55538921, -0.27324557,  0.03174584,  1.50372623],
       [ 1.14066792,  1.05780319,  1.8615576 ,  1.92744701],
       [ 1.77241262, -0.77838323,  1.16468625, -1.25869994],
       [-0.06301582, -1.58049865,  0.00710397, -0.75367861],
       [ 1.6650395 ,  1.4888026 , -0.09584691, -1.02133958],
       [ 0.6293576 , -1.40615392, -0.04812641, -0.16717914],
       [-0.58795762,  1.61760887,  0.87752655, -1.70496967],
       [ 0.38446047,  0.91300969,  0.35094352, -1.31367496]])

In [11]:
pf = PolynomialFeatures(degree, include_bias=True)
pf.fit(x)

PolynomialFeatures(degree=3)

In [12]:
pf.n_features_in_

4

In [13]:
pf.n_output_features_

35

In [14]:
pf.powers_

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [2, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 2],
       [3, 0, 0, 0],
       [2, 1, 0, 0],
       [2, 0, 1, 0],
       [2, 0, 0, 1],
       [1, 2, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 2, 0],
       [1, 0, 1, 1],
       [1, 0, 0, 2],
       [0, 3, 0, 0],
       [0, 2, 1, 0],
       [0, 2, 0, 1],
       [0, 1, 2, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 2],
       [0, 0, 3, 0],
       [0, 0, 2, 1],
       [0, 0, 1, 2],
       [0, 0, 0, 3]])

In [15]:
pf.get_feature_names_out()

array(['1', 'x0', 'x1', 'x2', 'x3', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3',
       'x1^2', 'x1 x2', 'x1 x3', 'x2^2', 'x2 x3', 'x3^2', 'x0^3',
       'x0^2 x1', 'x0^2 x2', 'x0^2 x3', 'x0 x1^2', 'x0 x1 x2', 'x0 x1 x3',
       'x0 x2^2', 'x0 x2 x3', 'x0 x3^2', 'x1^3', 'x1^2 x2', 'x1^2 x3',
       'x1 x2^2', 'x1 x2 x3', 'x1 x3^2', 'x2^3', 'x2^2 x3', 'x2 x3^2',
       'x3^3'], dtype=object)

In [16]:
pf.transform(x)

array([[ 1.00000000e+00, -2.83408027e-01, -3.56917339e-01,
        -7.50087248e-01,  4.26811795e-01,  8.03201096e-02,
         1.01153239e-01,  2.12580747e-01, -1.20961889e-01,
         1.27389987e-01,  2.67719144e-01, -1.52336530e-01,
         5.62630880e-01, -3.20146085e-01,  1.82168309e-01,
        -2.27633638e-02, -2.86676397e-02, -6.02470900e-02,
         3.42815702e-02, -3.61033447e-02, -7.58737544e-02,
         4.31733954e-02, -1.59454107e-01,  9.07319702e-02,
        -5.16279609e-02, -4.54676949e-02, -9.55536044e-02,
         5.43715489e-02, -2.00812716e-01,  1.14265689e-01,
        -6.50190279e-02, -4.22022248e-01,  2.40137496e-01,
        -1.36642125e-01,  7.77515829e-02],
       [ 1.00000000e+00, -3.60187022e-01,  6.49390801e-01,
         1.18606298e+00, -7.11732819e-01,  1.29734690e-01,
        -2.33902139e-01, -4.27204493e-01,  2.56356924e-01,
         4.21708413e-01,  7.70218390e-01, -4.62192745e-01,
         1.40674540e+00, -8.44159949e-01,  5.06563605e-01,
        -4.67

How many parameters have the following type of functions?
Can you write the corresponding hypothesis?
1. 5-variable linear function passing through the origin.
2. 3-variable quadratic function.
3. Bivariate cubic function.

**5-variable linear through origin**

$\theta_0 x_0 + \theta_1 x_1 + \theta_2 x_2 + \theta_3 x_3 + \theta_4 x_4$

**3-variable quadratic function**

$\theta_0 + \theta_1 x_0 + \theta_2 x_1 + \theta_3 x_2 + \theta_4 x_0^2 + \theta_5 x_0 x_1 + \theta_6 x_0 x_2 + \theta_7 x_1^2 + \theta_8 x_1 x_2 + \theta_9 x_2^2$

**2-variable cubic function**

$\theta_0 + \theta_1 x_0 + \theta_2 x_1 + \theta_3 x_0^2 + \theta_4 x_0 x_1 + \theta_5 x_1^2 + \theta_6 x_0^3 + \theta_7 x_0^2 x_1 + \theta_8 x_0 x_1^2 + \theta_9 x_1^3$